### ISSUE TITLE
WarpX: Fields Transposed

### ISSUE THREAD

**Issue by ax3l** [hightower8083/opmd2VTK#2] opened 2020-11-17 20:28 UTC
Hi,

@ayenpure and I currently investigate a bug that shows the WarpX fields exactly transposed.
In the image below, he (blue) particle beam is shown correctly, traveling along the Z direction. But the `E_y` field is exactly transposed - ideally it should overlap with the beam in parts.

![visit0000](https://user-images.githubusercontent.com/1353258/99443989-6c498c00-28d0-11eb-9f16-68ccd034fcf6.png)

The script that was used is `opmd2VTK_pyvtk`.

**Comment by hightower8083** [comment] 2020-11-17 21:29
Hi @ax3l and @ayenpure 

Thank you for your interest in the converter. 
I will need to check the issue and revise the code, but before that, could you please specify if you are using `master` or `dev` branch?  If you've used `master`, please switch to `dev`, since `master` is hopelessly outdated and should actually be removed.. I remember fixing the axes [issue](https://github.com/hightower8083/opmd2VTK/commit/db94fb46ce10ddb925c77ff08dbd931a36542a44) for `cartesian` geometry, so may be this will already address your problem.

One more remark -- the `pyvtk` interface is actually rather slow if compared to `tvtk` so if you don't mind installing `mayavi` (simplest but heavy way to get `tvtk`) i recommend switch to `tvtk`.

**Comment by ax3l** [comment] 2020-11-17 23:07
Oh no, I am on the `master` branch...

a quick-hack on top of the master branch that addresses the issue for 3D data (very dirty): https://github.com/ax3l/opmd2VTK/blob/fix-hackFieldsIntoParticleDomain/opmd2VTK/opmd2VTK_pyvtk.py

**Comment by ax3l** [comment] 2020-11-17 23:11
> If you've used master, please switch to dev, since master is hopelessly outdated and should actually be removed.. I remember fixing the axes issue for cartesian geometry, so may be this will already address your problem.

Oh wow, yes please feel free to go ahead and remove this. We used this by default.

> One more remark -- the pyvtk interface is actually rather slow if compared to tvtk so if you don't mind installing mayavi (simplest but heavy way to get tvtk) i recommend switch to tvtk.

Looks like there is a conda-forge package for it :tada: https://anaconda.org/conda-forge/mayavi

**Comment by hightower8083** [comment] 2020-11-17 23:29
Thanx for the hack, but really `master` is too ugly to fix)) sorry for keeping it.. 
in `dev` the code structure is way clearer and converter _api_ part is separated from _writer_, though still lots of space for improvements

and yes mayavi has finally made it conda after being stuck for years in Enthought Canopy =)

Let me know if `dev` fixes the issue!

**Comment by ax3l** [comment] 2020-11-17 23:48
`dev` looks better on first view on my machine :tada: 
but @ayenpure still sees some problems with pyvtk on his. I'll let him report here.

@ayenpure feel free to re-try with the `mayavi` script on the `dev` branch.

**Comment by ayenpure** [comment] 2020-11-18 06:36
@ax3l @hightower8083 I confirmed the scripts in dev work with both `tvtk` and `pyvtk`.
I had to rectify my python setup to get it to work :) Seems like I was using packages that did not like to work together.
I can report `tvtk` is much faster but produces outputs in `vti` files.
I wanted something that I can readily use in `VTK-m` so I settled with `pyvtk` for outputs to be in the `vtk` format.

**Comment by hightower8083** [comment] 2020-11-18 09:34
personally I used paraview, which does both legacy and xml (`.vti`, `.vtp` etc) formats, but  this `VTK-m` also looks interesting. In order to speed-up file writing with `pyvtk` interface be sure to use `format=binary` (should be default) and try `sample` argument to reduce the grid resolution.

I'll close this issue for now, but please don't hesitate to reopen it in case you see any bugs or have any suggestions -- i'm also reachable in openpmd slack channel.

**Closed as completed by hightower8083** 2020-11-18 09:34 UTC
